// The kiosk's pages are set in ParaType's PT family (SIL OFL, Cyrillic since
// 2009 — the type of Russian signage and print of the 2000s and 2010s).
// GitHub Pages serves the repo without a build step, so the Cyrillic and
// Latin woff2 subsets are copied next to the site, and their @font-face
// rules go to assets/css/pt-fonts.css. Run `npm run vendor:fonts` after
// updating @fontsource.
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = 'assets/fonts/pt';
const CSS = 'assets/css/pt-fonts.css';
const FAMILIES = [
  ['pt-sans', ['400', '700', '400-italic']],
  ['pt-sans-narrow', ['400', '700']],
  ['pt-mono', ['400']]
];
const SUBSETS = /-(cyrillic|latin)-\d{3}-(normal|italic) \*\//;

mkdirSync(OUT, { recursive: true });
const rules = [];
let files = 0;
for (const [family, styles] of FAMILIES) {
  const root = join('node_modules/@fontsource', family);
  copyFileSync(join(root, 'LICENSE'), join(OUT, `${family}-OFL.txt`));
  for (const style of styles) {
    const css = readFileSync(join(root, `${style}.css`), 'utf8');
    for (const block of css.split(/(?=\/\* )/)) {
      if (!SUBSETS.test(block)) continue;
      const woff2 = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
      copyFileSync(join(root, 'files', woff2), join(OUT, woff2));
      files += 1;
      rules.push(block.trim().replace(/src: [^;]+;/, `src: url('../fonts/pt/${woff2}') format('woff2');`));
    }
  }
}

writeFileSync(CSS, `/* Generated by scripts/vendor-fonts.mjs from @fontsource (SIL OFL 1.1). */\n\n${rules.join('\n\n')}\n`);
console.log(`PT fonts vendored: ${files} files`);
